version: '3'
services:
  social:
    build: 
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - 80:3000
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - 27014:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
